# default var file
---
#
# CentOS와 Ubuntu에 따라 버전 표기가 바뀜. 
#

# Kubernetes Package Version
k8s_version_ubuntu: =1.28.2-00
k8s_version_centos: 1.14.10-0

# Docker Package Version
docker_version_ubuntu: =5:24.0.7-1~ubuntu.20.04~focal
docker_version_centos: 18.06.3.ce-3.el7

# K8s Minor Number
k8s_minor_ver: "{{ k8s_version.split('.')[1] }}"

